Watch feature and tests
jupyterlab/jupyterlab-builder pull request #18
Opened 2024-07-05 15:04 UTC by cronan03

Command is working currently

2024-07-12 07:06 UTC, fcollonval commented
Hey @cronan03 could execute the linter on the PR: `python -m pre_commit run -a`

2024-07-13 07:58 UTC, fcollonval requested changes
Thanks @cronan03 

Minor suggestions but overall it looks good.

2024-07-13 07:58 UTC, fcollonval commented on jupyter_builder/extension_commands/watch.py
> +        # os.path.join(HERE, "staging"),
Let's drop unused code

```suggestion
```

2024-07-13 07:58 UTC, fcollonval commented on jupyter_builder/federated_extensions.py
> +    # core_path = osp.join(HERE, "staging") if core_path is None else str(Path(core_path).resolve())
```suggestion
```

2024-07-13 07:58 UTC, fcollonval commented on jupyter_builder/jlpm.py
> +"""A Jupyter-aware wrapper for the yarn package manager"""
It is a good practice to not mix up changes in a PR to focus on one bug fix or feature.

But let's keep it this time

2024-07-13 08:01 UTC, fcollonval commented
For the falling tests, could you execute the auto fix `python -m pre_commit run -a`

For the failing windows test, could you try increasing the sleep interval before checking the files changes. It may be all that is needed to fix the test.

2024-07-13 09:10 UTC, cronan03 commented on jupyter_builder/jlpm.py
> +"""A Jupyter-aware wrapper for the yarn package manager"""
Okay thanks @fcollonval , will keep that in mind

2024-07-15 09:54 UTC, fcollonval commented
Hey @cronan03 could you please not add the yarn.js file in this PR and create a new one for it?

2024-07-16 13:09 UTC, fcollonval approved these changes
Yeah let's merge

2024-07-16 13:09 UTC, merged